// Generated by CoffeeScript 1.9.1
(function() {
  $(function() {
    var mapTH2EN;
    mapTH2EN = function(s) {
      return s;
    };
    return $('#boxTH').on('keypress', function(e) {
      return $('#boxEN'.text(mapTH2EN($('#boxTH').text())));
    });
  });

}).call(this);

//# sourceMappingURL=script.js.map
